Milestone 3
Tresor11/Tic-Tac-Toe pull request #3
Opened 2019-11-27 17:48 UTC by WCanirinka

Code review

2019-11-27 19:48 UTC, stratospherique requested changes
### Great start @team :clap: :clap: However, some requirement needs to be implemented in order to get approval for this milestone. check :arrow_down: 

##### OOP design & Implementation details

* [x] The project uses at least two classes (Usually it uses three: Game, Board and Player). The code of the project should be logically divided between classes. 
  - :warning:  You should think of a way of decoupling the game into concepts that can be translated into classes (objects) that communicate between each others through messages (i.e methods)
* [x] All classes are kept in `lib` directory.
* [x] DRY rule should be respected. E.g. students tend to check winning position for X and O separately instead of creating a method and reuse it.
- **[SUGGESTION]** instead of using `victory1` & `victory2` to check for winning cases, I recommend refactoring your code as follows:

```ruby
class Game
  board = ['O', 'X', 'O', 'X', 'O', 'X', 'O', 'X', 'X']

  def check_win(player_symbol)
    # for rows
    all_equal(board[0..2], player_symbol) ||
    all_equal(board[3..5], player_symbol) ||
    all_equal(board[6..8], player_symbol)

    # and analogical as above for columns and diagonals
  end

  def all_equal(subarray, player_symbol)
    return true if subarray.uniq.size == 1 && subarray.uniq == player_symbol
  end
end
```

### That's it :relaxed: When finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2019-11-27 19:48 UTC, stratospherique commented on bin/main.rb
> +require './lib/logic.rb'
* [ ] Using `require_relative` for files in your directory instead of `require` is a ruby convention.

> "Require should be used for external files, like gems, while require_relative should be used for referring to files within your directory."

2019-11-27 20:57 UTC, WCanirinka commented
Request for review

2019-11-27 21:00 UTC, suretrust requested changes
Hi @WCanirinka and @Tresor11 ,

### Great job thus far, :raised_hands: however, there is still one correction requested by the previous TSE that you haven't made.

- [x] All classes are kept in the `lib` directory.

**Kindly submit for another code review once this has been fixed.** _Happy coding!_ :tada:

2019-11-27 23:56 UTC, Tresor11 commented
we kept all the classes in the lib directory as specified

2019-11-28 00:02 UTC, ebukaume approved these changes
## Approved!

Hi team :wave: 

You guys are doing very well. **You can now merge.**

[OPTIONAL]
Why do you prefer to have 2 classes in one file? Why not separate them into their individual files?

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

2019-11-28 00:03 UTC, Tresor11 commented
> ## Approved!
> Hi team 
> 
> You guys are doing very well. **You can now merge.**
> 
> [OPTIONAL]
> Why do you prefer to have 2 classes in one file? Why not separate them into their individual files?
> 
> Happy Coding 
> **Ebuka Umeokonkwo**
> [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

tha

2019-11-28 00:04 UTC, merged